# Generated by Django 4.2.16 on 2024-12-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, max_length=200, null=True, unique=True
            ),
        ),
    ]
