# Generated by Django 4.2.16 on 2024-12-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap", "0005_remove_category_region_region_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="hook_text",
        ),
        migrations.AddField(
            model_name="post",
            name="farm_owner",
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
