# Generated by Django 4.2.16 on 2024-12-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap", "0007_dailytomatodata_realtimetomatodata_tomatopost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, max_length=200, null=True
            ),
        ),
    ]
