# Generated by Django 4.2.16 on 2024-12-23 02:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tap", "0009_farm"),
    ]

    operations = [
        migrations.RenameField(
            model_name="farm",
            old_name="name",
            new_name="farm",
        ),
        migrations.AddField(
            model_name="farm",
            name="owner",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
