# Generated by Django 4.2.16 on 2024-12-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap", "0010_rename_name_farm_farm_farm_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="owner",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
