# Generated by Django 4.2.16 on 2024-12-23 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tap", "0013_alter_farm_farm_alter_farm_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="farm",
            old_name="owner",
            new_name="farm_owner",
        ),
    ]
