# Generated by Django 4.2.16 on 2024-12-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap", "0014_rename_owner_farm_farm_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="owner_image",
            field=models.ImageField(blank=True, upload_to="farm/images/%Y/%m/%d/"),
        ),
    ]
