# Generated by Django 4.2.16 on 2024-12-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tap", "0015_farm_owner_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tomatopost",
            name="csv_file",
        ),
        migrations.AddField(
            model_name="tomatopost",
            name="file_upload",
            field=models.FileField(blank=True, upload_to="blog/files/%Y/%m/%d/"),
        ),
    ]
